apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: watchlist_db
            - name: POSTGRES_USER
              value: watchlist_user
            - name: POSTGRES_PASSWORD
              value: watchlist_pass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: watchlist
spec:
  selector:
    app: postgres
  ports:
    - port: 5432